package org.byteam.delta;
/**
 * Used to generate <code>org/byteam/delta/AppInfo.java</code>
 * <p>
 * Created by Cheney on 16/9/19.
 */
class AppInfoTemplate {
    String applicationId
    String applicationClass

    def getTemplate() {
        return """package org.byteam.delta;

/** Auto generated by delta. Do not modify or move it. */
public class AppInfo {
    public static final String applicationId = "$applicationId";
    public static final String applicationClass = "$applicationClass";
}
"""
    }
}